Fix wrong path

diff --git a/.github/workflows/py-nox-ci.yml b/.github/workflows/py-nox-ci.yml
--- a/.github/workflows/py-nox-ci.yml
+++ b/.github/workflows/py-nox-ci.yml
@@ -24,10 +24,13 @@ jobs:
 
       - name: Set up Nox
         run: |
-          if [ -f ./path/to/noxfile/noxfile.py ]; then
-            echo "NOXFILE_PATH=./ingestion/noxfile.py" >> $GITHUB_ENV
+          NOXFILE="./path/to/noxfile/noxfile.py"
+          if [ -f "$NOXFILE" ]; then
+            echo "NOXFILE_PATH=$NOXFILE" >> $GITHUB_ENV
+            echo "noxfile found, environment variable set."
           else
-            echo "noxfile.py not found!" && exit 1
+            echo "Error: noxfile.py not found at $NOXFILE"
+            exit 1
           fi
           # Install uv to speed up virtual environments installation
           curl -LsSf https://astral.sh/uv/install.sh | sh
